apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
spec:
  rules:
    - host: ujwal.pv
      http:
        paths:
          - path: /
            pathType: "Prefix"
            backend:
              service:
                name: "api-service"
                port:
                  number: 80
          - path: /nginx
            pathType: "Prefix"
            backend:
              service:
                name: "nginx-service"
                port:
                  number: 80                  
